# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0003_auto_20180326_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='down_count',
            new_name='voteup',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='up_count',
        ),
    ]
