# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0005_auto_20180329_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='ask_app.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='question', to='ask_app.Topic'),
        ),
    ]
