# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anyaskuser',
            name='description',
        ),
        migrations.AddField(
            model_name='anyaskuser',
            name='image',
            field=models.ImageField(default='image/user/default.png', upload_to='image/user/'),
        ),
    ]
